# Generated by Django 4.2.16 on 2024-09-21 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_lesson_video_url'),
        ('users', '0003_remove_user_is_content_manager_alter_user_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_pay', models.DateField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('sum_paid', models.IntegerField(blank=True, null=True, verbose_name='Сумма оплаты')),
                ('payment_method', models.CharField(blank=True, choices=[('card', 'Карта'), ('cash', 'Наличные')], max_length=4, null=True, verbose_name='Способ оплаты')),
                ('paid_course', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_course_user', to='university.course', verbose_name='Курс')),
                ('paid_lesson', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_lesson_user', to='university.lesson', verbose_name='Урок')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
