# Generated by Django 4.2.16 on 2024-09-21 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pay'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
