# Generated by Django 4.2.16 on 2024-09-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_pay_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Карта'), ('cash', 'Наличные')], max_length=4, null=True, verbose_name='Способ оплаты'),
        ),
    ]
