# Generated by Django 4.2.16 on 2024-09-21 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_alter_lesson_course'),
        ('users', '0007_alter_pay_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='paid_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_course_user', to='university.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='paid_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_lesson_user', to='university.lesson', verbose_name='Урок'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта')], max_length=4, null=True, verbose_name='Способ оплаты'),
        ),
    ]
