# Generated by Django 4.2.16 on 2024-09-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_pay_paid_course_alter_pay_paid_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Карта'), ('cash', 'Наличные')], max_length=4, null=True, verbose_name='Способ оплаты'),
        ),
    ]
