# Generated by Django 4.2.16 on 2024-09-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_pay_status_paid_pay_url_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('card', 'Карта'), ('cash', 'Наличные')], max_length=4, null=True, verbose_name='Способ оплаты'),
        ),
    ]
