# Generated by Django 4.2.16 on 2024-09-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_pay_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('card', 'Карта')], max_length=4, null=True, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='url_paid',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на оплату'),
        ),
    ]
