# Generated by Django 4.2.16 on 2024-09-28 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_pay_payment_method_alter_pay_url_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pay',
            old_name='user',
            new_name='owner',
        ),
    ]
