# Generated by Django 4.2.16 on 2024-10-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_pay_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего входа'),
        ),
    ]
