# Generated by Django 4.2.16 on 2024-09-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_URL',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
