# Generated by Django 4.2.16 on 2024-09-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0005_remove_lesson_course_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(to='university.course', verbose_name='Курс'),
        ),
    ]
