# Generated by Django 4.2.16 on 2024-09-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_course_price_lesson_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID продукта в STRIPE'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID продукта в STRIPE'),
        ),
    ]
