# Generated by Django 4.2.16 on 2024-09-28 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_course_stripe_id_lesson_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='stripe_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кэшированная стоимость'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='stripe_price',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кэшированная стоимость'),
        ),
    ]
