# Generated by Django 4.2.16 on 2024-09-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_course_stripe_price_lesson_stripe_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='stripe_price',
            new_name='stripe_price_id',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='stripe_price',
            new_name='stripe_price_id',
        ),
    ]
